FROM jenkins/jenkins:lts

USER root

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    ca-certificates curl git bash rsync \
 && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
 && apt-get install -y --no-install-recommends nodejs \
 && node -v \
 && npm -v \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

USER jenkins
